---
apiVersion: glusterd-operator.storage/v1
kind: GlusterdStorage
metadata:
  # This will be used as name of PV Hosting Volume
  name: storage-pool-1
spec:
  type: Dispersed
  nodes:
    - name: raspberrypi-server
      path: "/tmp/test"
    - name: kevin-elite
      path: "/tmp/test"
