---
apiVersion: glusterd-operator.storage/v1
kind: GlusterdStorage
metadata:
  # This will be used as name of PV Hosting Volume
  name: ssd-storage
spec:
  type: Arbiter
  nodes:
    - name: kevin-laptop
      path: "/data/glusterfs/ssd-storage"
    - name: rpi-server2
      path: "/data/glusterfs/ssd-storage"
    - name: raspberrypi-server
      path: "/data/glusterfs/ssd-storage-arbiter"
