---
apiVersion: glusterd-operator.storage/v1
kind: GlusterdStorage
metadata:
  # This will be used as name of PV Hosting Volume
  name: storage-pool-2
spec:
  name: gv1
  type: Replica
  nodes:
    - name: raspberrypi-server
      path: "/tmp/test2"
    - name: rpi-server2
      path: "/tmp/test2"
